CREATE OR REPLACE DATABASE MY_DATABASE;
CREATE OR REPLACE SCHEMA MY_DATABASE.MY_SCHEMA;
CREATE OR REPLACE TABLE MY_DATABASE.MY_SCHEMA.MY_TABLE (ID INTEGER, DESC STRING, LOAD_TIMESTAMP TIMESTAMP_TZ) AS SELECT * FROM VALUES (1, 'Shirt', CURRENT_TIMESTAMP()), (2, 'Trousers', CURRENT_TIMESTAMP()), (3, 'Shoes', CURRENT_TIMESTAMP()), (3, 'Shoes', CURRENT_TIMESTAMP());
CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_NOTIFICATION_INTEGRATION TYPE = EMAIL ENABLED = TRUE ALLOWED_RECIPIENTS = ('santiagourgelolea@gmail.com');

SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.ALERT_HISTORY(SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP()))) ORDER BY SCHEDULED_TIME;

CREATE OR REPLACE ALERT MY_DATABASE.MY_SCHEMA.DUPLICATES_ALERT WAREHOUSE = COMPUTE_WH SCHEDULE = '5 MINUTES'
IF(EXISTS((SELECT ID, COUNT(*) AS RECORDS FROM MY_DATABASE.MY_SCHEMA.MY_TABLE GROUP BY ID HAVING COUNT(*) > 1)))
THEN CALL SYSTEM$SEND_EMAIL ('EMAIL_NOTIFICATION_INTEGRATION', 'santiagourgelolea@gmail.com', 'Alert: Duplicates', 'There are duplicates for PK in MY_DATABASE.MY_SCHEMA.MY_TABLE table. Please check MY_DATABASE.MY_SCHEMA.MY_TABLE_DUPLICATES table.');
ALTER ALERT MY_DATABASE.MY_SCHEMA.DUPLICATES_ALERT RESUME; -- SUSPEND

CREATE OR REPLACE PROCEDURE MY_DATABASE.MY_SCHEMA.PR_LOG_NOTIFY_DUPLICATES (START_TS TIMESTAMP_TZ, END_TS TIMESTAMP_TZ) RETURNS STRING LANGUAGE SQL EXECUTE AS CALLER AS $$
  BEGIN
    EXECUTE IMMEDIATE '
      CREATE OR REPLACE TABLE MY_DATABASE.MY_SCHEMA.MY_TABLE_DUPLICATES AS
      SELECT * FROM MY_DATABASE.MY_SCHEMA.MY_TABLE
      WHERE ID IN (SELECT ID FROM (SELECT ID, COUNT(*) AS RECORDS FROM MY_DATABASE.MY_SCHEMA.MY_TABLE GROUP BY ID HAVING COUNT(*) > 1)) AND LOAD_TIMESTAMP BETWEEN ''' || START_TS || ''' AND ''' || END_TS || '''';
      CALL SYSTEM$SEND_EMAIL ('EMAIL_NOTIFICATION_INTEGRATION', 'santiagourgelolea@gmail.com', 'Alert: Duplicates', 'There are duplicates for PK in MY_DATABASE.MY_SCHEMA.MY_TABLE table. Please check MY_DATABASE.MY_SCHEMA.MY_TABLE_DUPLICATES table.');
    RETURN 'Data capture and notification successfully completed';
  END;
$$;